### ISSUE TITLE
Integration with VolunteerDashboard

### ISSUE THREAD

**Issue by coventry** [Bernie-2016/EventCounter#4] opened 2015-11-03 01:07 UTC
Some things which need to happen for good integration with VolunteerDashboard.  Probably the most relevant code from the Dashboard is [here](https://github.com/Bernie-2016/VolunteerDashboard/blob/master/src/js/dashboard.js#L93).
- The endpoint needs to break out the counts by event type as well as by region, and give the regional totals.  This means the database schema has to include the event type as a column.
- It needs to know about the state-level and Craigslist regions, so that requests don't have to send across thousands of  zip codes.  This would be another good thing to include as a database column, so that the computation is done up front.

**Comment by saikat** [comment] 2015-11-04 03:03
Closing this as dupe of https://github.com/Bernie-2016/VolunteerDashboard/issues/2

**Comment by saikat** [comment] 2015-11-04 03:03
(But referring to this here so rapi knows what to do)

**Closed as completed by saikat** 2015-11-04 03:03 UTC
